### ISSUE TITLE
Query parameters are not handled

### ISSUE THREAD

**Issue by kptdobe** [adobe/petridish#46]
Request http://localhost:3000/index.html?debug=true
-> debug=true does not appear in the `payload` nor in the `secrets`

**Comment by kptdobe** [comment]
Follow up of the discussion here: https://github.com/adobe/hypermedia-pipeline/pull/34#issuecomment-416966706

**Comment by tripodsan** [comment]
well, external query (/index.html?debug=true) is passed to fastly (petridish), which requests the action with his own parameters.eg:

```
https://runtime.adobe.io/api/v1/web/tripod/default/git-github-com-tripodsan-hlxtest-git--dirty--dump_html?path=/index.md&owner=tripodsan&repo=hlxtest&ref=master
```

in VCL:
```
      # Invoke OpenWhisk
      set req.url = "/api/v1/web" + var.action + "?owner=" + var.owner + "&repo=" + var.repo + "&ref=" + var.ref + "&path=" + var.dir + "/" + var.name + ".md" + "&selector=" + var.selector + "&extension=" + req.url.ext + "&branch=" + var.branch + "&strain=" + var.strain + "&GITHUB_KEY=" + table.lookup(secrets, "GITHUB_TOKEN");
```

**Comment by tripodsan** [comment]
If we want to pass the external request headers and parameters into the action, we probably need to add them to the request URL with an additional parameter. eg: 

`&req=<some encoded json of headers and params>`

**Comment by kptdobe** [comment]
Yes, that's why I expected in the `payload` that the `request` property represents the original request. At the moment, it represents the request to the action.
Your previous comment
> looking at https://github.com/adobe/openwhisk-loggly-wrapper/blob/master/wrap.js#L95, I think the params are already in secrets
That's not the case in Petridish (did not check on fastly). But I do not think it is a good idea to put them in the secrets anyway, this would not be natural to have them here, especially when coding the `pre.js` ...

**Comment by tripodsan** [comment]
I created a dump.pre.js:

```
payload.request: {
  "headers": {
    "x-forwarded-port": "443",
    "accept": "*/*",
    "user-agent": "curl/7.54.0",
    "x-forwarded-proto": "https",
    "host": "controller-a",
    "perf-br-req-in": "1535616883.669",
    "connection": "close",
    "x-forwarded-for": "202.32.93.230"
  },
  "params": {
    "path": "/index.md",
    "ref": "master",
    "__ow_path": "",
    "owner": "tripodsan",
    "repo": "hlxtest"
  },
  "method": "get"
}

config: {
  "LOGGLY_KEY": ...,
  "LOGGLY_HOST": ...,
  "logger": ...
}
```

**Comment by tripodsan** [comment]
I think, too:

`payload.request` should contain the original (external) request
`config.params` should contain the original action params 
`config.secrets` should contain the unmodifiable action params

**Comment by kptdobe** [comment]
Having both would help us to "trace" the requests, headers... and provide debug info.

**Comment by tripodsan** [comment]
> why not having 2 complete request objects (headers, params, method, url, protocol...),
you already get the openwhisk ones through the `_ow_*` params:

- __ow_method (type: string): the HTTP method of the request.
- __ow_headers (type: map string to string): the request headers.
- __ow_path (type: string): the unmatched path of the request (matching stops after consuming the action extension).
...

**Comment by kptdobe** [comment]
Correct. With a bit of clean up (like grouping all those __ow in one object) and changing the `request` object to become the original request, we should be good then.

**Comment by tripodsan** [comment]
but we could "explode" the _ow_* ones into the request object. and maybe, we should rename the `config` to `action`... I used `config` because I didn't had a better name. so maybe:

```js
pre(payload, action) { 
   ... 
} 
```

| argument | comment |
|-----------|----------|
| `payload.request` | should contain the original (external) request |
| `payload.request.params` | external request params |
| `payload.request.headers` | external request headers |
| `payload.request.method` | external request method |
| `payload.request.url` | external request url |
| `action.request.params` | internal action request params |
| `action.request.path` | internal action request path |
| `action.request.headers` | internal action request headers |
| `action.secrets` | should contain the unmodifiable action params |
| `action.logger` | contains the logger |

**Comment by kptdobe** [comment]
Well, that's almost what I proposed :)
I like this proposal because the `payload` is what you would need in 99% of the cases (+/- the logger but that's discussed somewhere else). If you have more specific needs (like knowing which repo / branch to do more advanced stuff), you may need to look at the `action`.

**Comment by tripodsan** [comment]
> Well, that's almost what I proposed :)

I know... I just merged and summarized our thoughts.

**Comment by tripodsan** [comment]
@trieloff WDYT?
