### ISSUE TITLE
Generate Request ID

### ISSUE THREAD

**Issue by trieloff** [adobe/petridish#66]
Fastly and OpenWhisk generate both request and invocation IDs. We should do the same, so that adobe/hypermedia-pipeline#61 can use the request ID instead of the time stamp to tag context dumps. In addition, #17 can then look up dumps from the current request and show them.

**Comment by tripodsan** [comment]
@trieloff what should be the name of the header ?

**Comment by trieloff** [comment]
These are the headers we have right now:

```
< x-openwhisk-activation-id: d1ba8f388c7a4ef0ba8f388c7a8ef06f
< x-request-id: QIp6naPQ7b2FcYiBJG2IqUJuNXmzOm6M
< x-backend-name: 3t7g8apsfQlFyvuHIQn9e8--F_AdobeRuntime
< x-cdn-request-id: 96e14a51-f48e-4978-b9bd-e2154bd0d831
```

`X-CDN-Request-ID` (note the capitalization) is the most important.

https://github.com/adobe/helix-cli/blob/9c5c3a1d87992a18494c12c5bd243ee7ae07b8f3/layouts/fastly/helix.vcl#L158-L160

`X-Backend-Name: localhost--F_Petridish` would be a nice touch.

`X-OpenWhisk-Activation-Id` and `X-Request-Id` are generated by OpenWhisk, so that would be a nice touch.

**Comment by trieloff** [comment]
Related adobe/helix-cli#251
