### ISSUE TITLE
Allow passing a logger

### ISSUE THREAD

**Issue by trieloff** [adobe/petridish#77]
In line with adobe/helix-cli#79 we need a way to pass in a logger to HelixServer, etc. The existing logger should remain as a default fallback.

**Comment by tripodsan** [comment]
it somehow feels wrong to pass down the logger instance. at it doesn't allow for a more finegraned distinction. e.g. if petridish want to log to an `access.log` it would need to instantiate the logger anyways differently. but for now, I don't see a better alternative.

**Comment by trieloff** [comment]
We can look a bit deeper into Winston, there might be a way to have derived loggers, so that we can tag each log statement with the origin, e.g.

`[hlx] [petridish] [pipeline] [htl] info: nothing important`

**Comment by tripodsan** [comment]
or use https://www.npmjs.com/package/bunyan :-) 
bunyan is also a good headless logger. which some nice log formats.
