### ISSUE TITLE
Extract `src/config` to a new package: helix-config

### ISSUE THREAD

**Issue by tripodsan** [adobe/petridish#80]
the code in `src/config` is used in helix-cli and petridish. as it should not be part of petridish, I suggest to move it to it's own repo.

### suggest
- `helix-config`
- `helix-shared`

**Comment by tripodsan** [comment]
@trieloff can you create a new repo `helix-shared` ? I started a template repository here:
https://github.com/adobe-rnd/helix-new-repository-template I will later merge in the source.

**Comment by stefan-guggisberg** [comment]
done: https://github.com/adobe/helix-shared

**Comment by tripodsan** [comment]
thanks!

**Comment by tripodsan** [comment]
npm release: https://www.npmjs.com/package/@adobe/helix-shared
